name: Mi Primer Workflow

on:
  push:
    branches: [ "main" ]  # Se ejecuta cada vez que haces push a main

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Ejecutar un script simple
        run: echo "¡El workflow se ha ejecutado con éxito!"
